/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_Subtask = 2,
  anon_sym_RBRACK = 3,
  anon_sym_ATextends = 4,
  anon_sym_subtask = 5,
  anon_sym_ATvalidator = 6,
  anon_sym_SEMI = 7,
  anon_sym_copy = 8,
  anon_sym_echo = 9,
  sym_word = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_string_literal_token1 = 12,
  sym_group_name = 13,
  sym_number = 14,
  sym_comment = 15,
  anon_sym_LF = 16,
  sym_source_file = 17,
  sym_subtask = 18,
  sym_subtask_header = 19,
  sym_item = 20,
  sym_directive = 21,
  sym_extends = 22,
  sym_validator = 23,
  sym_command = 24,
  sym_copy = 25,
  sym_echo = 26,
  sym_script = 27,
  sym_arg = 28,
  sym_string_literal = 29,
  sym__newline = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_subtask_repeat1 = 32,
  aux_sym_echo_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_Subtask] = "Subtask",
  [anon_sym_RBRACK] = "]",
  [anon_sym_ATextends] = "@extends",
  [anon_sym_subtask] = "subtask",
  [anon_sym_ATvalidator] = "@validator",
  [anon_sym_SEMI] = ";",
  [anon_sym_copy] = "copy",
  [anon_sym_echo] = "echo",
  [sym_word] = "word",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_group_name] = "group_name",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [anon_sym_LF] = "\n",
  [sym_source_file] = "source_file",
  [sym_subtask] = "subtask",
  [sym_subtask_header] = "subtask_header",
  [sym_item] = "item",
  [sym_directive] = "directive",
  [sym_extends] = "extends",
  [sym_validator] = "validator",
  [sym_command] = "command",
  [sym_copy] = "copy",
  [sym_echo] = "echo",
  [sym_script] = "script",
  [sym_arg] = "arg",
  [sym_string_literal] = "string_literal",
  [sym__newline] = "_newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_subtask_repeat1] = "subtask_repeat1",
  [aux_sym_echo_repeat1] = "echo_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_Subtask] = anon_sym_Subtask,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_ATextends] = anon_sym_ATextends,
  [anon_sym_subtask] = anon_sym_subtask,
  [anon_sym_ATvalidator] = anon_sym_ATvalidator,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_copy] = anon_sym_copy,
  [anon_sym_echo] = anon_sym_echo,
  [sym_word] = sym_word,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_group_name] = sym_group_name,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [anon_sym_LF] = anon_sym_LF,
  [sym_source_file] = sym_source_file,
  [sym_subtask] = sym_subtask,
  [sym_subtask_header] = sym_subtask_header,
  [sym_item] = sym_item,
  [sym_directive] = sym_directive,
  [sym_extends] = sym_extends,
  [sym_validator] = sym_validator,
  [sym_command] = sym_command,
  [sym_copy] = sym_copy,
  [sym_echo] = sym_echo,
  [sym_script] = sym_script,
  [sym_arg] = sym_arg,
  [sym_string_literal] = sym_string_literal,
  [sym__newline] = sym__newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_subtask_repeat1] = aux_sym_subtask_repeat1,
  [aux_sym_echo_repeat1] = aux_sym_echo_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Subtask] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATextends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_subtask] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATvalidator] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_echo] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_group_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_subtask] = {
    .visible = true,
    .named = true,
  },
  [sym_subtask_header] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_directive] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_extends] = {
    .visible = true,
    .named = true,
  },
  [sym_validator] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_copy] = {
    .visible = true,
    .named = true,
  },
  [sym_echo] = {
    .visible = true,
    .named = true,
  },
  [sym_script] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subtask_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_echo_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_command = 1,
  field_header = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_command] = "command",
  [field_header] = "header",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_header, 0},
  [1] =
    {field_command, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 22,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 21,
  [37] = 37,
  [38] = 38,
  [39] = 34,
  [40] = 37,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_directive,
  sym_item,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_directive] = {.index = 0, .length = 2},
  [sym_item] = {.index = 2, .length = 3},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_extends,
    sym_validator,
  [2] =
    anon_sym_LF,
    sym_command,
    sym_directive,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '\n', 66,
        '"', 58,
        '#', 64,
        ';', 45,
        '@', 12,
        'S', 32,
        '[', 39,
        ']', 41,
        'c', 20,
        'e', 9,
        's', 33,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(66);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '#') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '#') ADVANCE(56);
      if (lookahead == 'c') ADVANCE(52);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == 'v') ADVANCE(3);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(40);
      END_STATE();
    case 17:
      if (lookahead == 'k') ADVANCE(43);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 34:
      if (lookahead == 'x') ADVANCE(28);
      END_STATE();
    case 35:
      if (lookahead == 'y') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '\n') ADVANCE(66);
      if (lookahead == '#') ADVANCE(64);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_Subtask);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_ATextends);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_subtask);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_ATvalidator);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_copy);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_copy);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_echo);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_echo);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'h') ADVANCE(53);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'o') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'o') ADVANCE(49);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'p') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'y') ADVANCE(47);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '"') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(65);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\\') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_group_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 37},
  [3] = {.lex_state = 37},
  [4] = {.lex_state = 37},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 37},
  [7] = {.lex_state = 37},
  [8] = {.lex_state = 37},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 37},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 37},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 37},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 60},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 60},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_Subtask] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_ATextends] = ACTIONS(1),
    [anon_sym_subtask] = ACTIONS(1),
    [anon_sym_ATvalidator] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_copy] = ACTIONS(1),
    [anon_sym_echo] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(31),
    [sym_subtask] = STATE(17),
    [sym_subtask_header] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_ATextends,
    ACTIONS(14), 1,
      anon_sym_ATvalidator,
    ACTIONS(17), 1,
      sym_group_name,
    ACTIONS(20), 1,
      anon_sym_LF,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(2), 2,
      sym_item,
      aux_sym_subtask_repeat1,
    STATE(6), 2,
      sym_extends,
      sym_validator,
    STATE(7), 3,
      sym_directive,
      sym_command,
      sym__newline,
  [33] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_ATextends,
    ACTIONS(27), 1,
      anon_sym_ATvalidator,
    ACTIONS(29), 1,
      sym_group_name,
    ACTIONS(31), 1,
      anon_sym_LF,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(4), 2,
      sym_item,
      aux_sym_subtask_repeat1,
    STATE(6), 2,
      sym_extends,
      sym_validator,
    STATE(7), 3,
      sym_directive,
      sym_command,
      sym__newline,
  [66] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_ATextends,
    ACTIONS(27), 1,
      anon_sym_ATvalidator,
    ACTIONS(29), 1,
      sym_group_name,
    ACTIONS(31), 1,
      anon_sym_LF,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(2), 2,
      sym_item,
      aux_sym_subtask_repeat1,
    STATE(6), 2,
      sym_extends,
      sym_validator,
    STATE(7), 3,
      sym_directive,
      sym_command,
      sym__newline,
  [99] = 8,
    ACTIONS(35), 1,
      anon_sym_copy,
    ACTIONS(37), 1,
      anon_sym_echo,
    ACTIONS(39), 1,
      sym_word,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym_comment,
    STATE(9), 1,
      sym_arg,
    STATE(21), 1,
      sym_string_literal,
    STATE(26), 3,
      sym_copy,
      sym_echo,
      sym_script,
  [126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_ATextends,
      anon_sym_ATvalidator,
      sym_group_name,
      anon_sym_LF,
  [138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_ATextends,
      anon_sym_ATvalidator,
      sym_group_name,
      anon_sym_LF,
  [150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_ATextends,
      anon_sym_ATvalidator,
      sym_group_name,
      anon_sym_LF,
  [162] = 6,
    ACTIONS(39), 1,
      sym_word,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LF,
    STATE(21), 1,
      sym_string_literal,
    STATE(12), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [182] = 6,
    ACTIONS(39), 1,
      sym_word,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_LF,
    STATE(21), 1,
      sym_string_literal,
    STATE(14), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_ATextends,
      anon_sym_ATvalidator,
      sym_group_name,
      anon_sym_LF,
  [214] = 6,
    ACTIONS(39), 1,
      sym_word,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LF,
    STATE(21), 1,
      sym_string_literal,
    STATE(16), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [234] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_ATextends,
      anon_sym_ATvalidator,
      sym_group_name,
      anon_sym_LF,
  [246] = 6,
    ACTIONS(39), 1,
      sym_word,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_LF,
    STATE(21), 1,
      sym_string_literal,
    STATE(16), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_ATextends,
      anon_sym_ATvalidator,
      sym_group_name,
      anon_sym_LF,
  [278] = 6,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_word,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      anon_sym_LF,
    STATE(21), 1,
      sym_string_literal,
    STATE(16), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [298] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_subtask_header,
    STATE(18), 2,
      sym_subtask,
      aux_sym_source_file_repeat1,
  [315] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      anon_sym_LBRACK,
    STATE(3), 1,
      sym_subtask_header,
    STATE(18), 2,
      sym_subtask,
      aux_sym_source_file_repeat1,
  [332] = 5,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_word,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    STATE(23), 1,
      sym_arg,
    STATE(36), 1,
      sym_string_literal,
  [348] = 5,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_word,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      sym_arg,
    STATE(36), 1,
      sym_string_literal,
  [364] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_word,
    ACTIONS(86), 2,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [375] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_word,
    ACTIONS(90), 2,
      anon_sym_DQUOTE,
      anon_sym_LF,
  [386] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_LF,
    STATE(8), 1,
      sym__newline,
  [396] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_LF,
    STATE(13), 1,
      sym__newline,
  [406] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_LF,
    STATE(11), 1,
      sym__newline,
  [416] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LF,
    STATE(15), 1,
      sym__newline,
  [426] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LF,
  [433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_SEMI,
  [440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_Subtask,
  [447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_subtask,
  [454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
  [461] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_LF,
  [468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_RBRACK,
  [475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
  [482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_number,
  [489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_LF,
  [496] = 2,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(116), 1,
      aux_sym_string_literal_token1,
  [503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_number,
  [510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
  [517] = 2,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(122), 1,
      aux_sym_string_literal_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 138,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 162,
  [SMALL_STATE(10)] = 182,
  [SMALL_STATE(11)] = 202,
  [SMALL_STATE(12)] = 214,
  [SMALL_STATE(13)] = 234,
  [SMALL_STATE(14)] = 246,
  [SMALL_STATE(15)] = 266,
  [SMALL_STATE(16)] = 278,
  [SMALL_STATE(17)] = 298,
  [SMALL_STATE(18)] = 315,
  [SMALL_STATE(19)] = 332,
  [SMALL_STATE(20)] = 348,
  [SMALL_STATE(21)] = 364,
  [SMALL_STATE(22)] = 375,
  [SMALL_STATE(23)] = 386,
  [SMALL_STATE(24)] = 396,
  [SMALL_STATE(25)] = 406,
  [SMALL_STATE(26)] = 416,
  [SMALL_STATE(27)] = 426,
  [SMALL_STATE(28)] = 433,
  [SMALL_STATE(29)] = 440,
  [SMALL_STATE(30)] = 447,
  [SMALL_STATE(31)] = 454,
  [SMALL_STATE(32)] = 461,
  [SMALL_STATE(33)] = 468,
  [SMALL_STATE(34)] = 475,
  [SMALL_STATE(35)] = 482,
  [SMALL_STATE(36)] = 489,
  [SMALL_STATE(37)] = 496,
  [SMALL_STATE(38)] = 503,
  [SMALL_STATE(39)] = 510,
  [SMALL_STATE(40)] = 517,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask, 1, 0, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask, 2, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_validator, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script, 1, 0, 2),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script, 2, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask_header, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_echo_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_echo_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_echo_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [106] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copy, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_testplan(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "testplan",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
