/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_Subtask = 2,
  anon_sym_RBRACK = 3,
  anon_sym_ATextends = 4,
  anon_sym_subtask = 5,
  anon_sym_ATvalidator = 6,
  anon_sym_SEMI = 7,
  anon_sym_copy = 8,
  anon_sym_echo = 9,
  sym_word = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_string_literal_token1 = 12,
  sym_group_name = 13,
  sym_number = 14,
  sym_comment = 15,
  anon_sym_LF = 16,
  sym_source_file = 17,
  sym_subtask = 18,
  sym_subtask_header = 19,
  sym_item = 20,
  sym_directive = 21,
  sym_extends = 22,
  sym_validator = 23,
  sym_command = 24,
  sym_copy = 25,
  sym_echo = 26,
  sym_script = 27,
  sym_arg = 28,
  sym_string_literal = 29,
  sym__newline = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_subtask_repeat1 = 32,
  aux_sym_echo_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_Subtask] = "Subtask",
  [anon_sym_RBRACK] = "]",
  [anon_sym_ATextends] = "@extends",
  [anon_sym_subtask] = "subtask",
  [anon_sym_ATvalidator] = "@validator",
  [anon_sym_SEMI] = ";",
  [anon_sym_copy] = "copy",
  [anon_sym_echo] = "echo",
  [sym_word] = "word",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_group_name] = "group_name",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [anon_sym_LF] = "\n",
  [sym_source_file] = "source_file",
  [sym_subtask] = "subtask",
  [sym_subtask_header] = "subtask_header",
  [sym_item] = "item",
  [sym_directive] = "directive",
  [sym_extends] = "extends",
  [sym_validator] = "validator",
  [sym_command] = "command",
  [sym_copy] = "copy",
  [sym_echo] = "echo",
  [sym_script] = "script",
  [sym_arg] = "arg",
  [sym_string_literal] = "string_literal",
  [sym__newline] = "_newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_subtask_repeat1] = "subtask_repeat1",
  [aux_sym_echo_repeat1] = "echo_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_Subtask] = anon_sym_Subtask,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_ATextends] = anon_sym_ATextends,
  [anon_sym_subtask] = anon_sym_subtask,
  [anon_sym_ATvalidator] = anon_sym_ATvalidator,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_copy] = anon_sym_copy,
  [anon_sym_echo] = anon_sym_echo,
  [sym_word] = sym_word,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_group_name] = sym_group_name,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [anon_sym_LF] = anon_sym_LF,
  [sym_source_file] = sym_source_file,
  [sym_subtask] = sym_subtask,
  [sym_subtask_header] = sym_subtask_header,
  [sym_item] = sym_item,
  [sym_directive] = sym_directive,
  [sym_extends] = sym_extends,
  [sym_validator] = sym_validator,
  [sym_command] = sym_command,
  [sym_copy] = sym_copy,
  [sym_echo] = sym_echo,
  [sym_script] = sym_script,
  [sym_arg] = sym_arg,
  [sym_string_literal] = sym_string_literal,
  [sym__newline] = sym__newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_subtask_repeat1] = aux_sym_subtask_repeat1,
  [aux_sym_echo_repeat1] = aux_sym_echo_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Subtask] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATextends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_subtask] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATvalidator] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_echo] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_group_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_subtask] = {
    .visible = true,
    .named = true,
  },
  [sym_subtask_header] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_directive] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_extends] = {
    .visible = true,
    .named = true,
  },
  [sym_validator] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_copy] = {
    .visible = true,
    .named = true,
  },
  [sym_echo] = {
    .visible = true,
    .named = true,
  },
  [sym_script] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subtask_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_echo_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_command = 1,
  field_header = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_command] = "command",
  [field_header] = "header",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_header, 0},
  [1] =
    {field_command, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 18,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 17,
  [38] = 31,
  [39] = 24,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_directive,
  sym_item,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_directive] = {.index = 0, .length = 2},
  [sym_item] = {.index = 2, .length = 2},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_extends,
    sym_validator,
  [2] =
    sym_command,
    sym_directive,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '"', 60,
        '#', 66,
        ';', 47,
        '@', 14,
        'S', 34,
        '[', 41,
        ']', 43,
        'c', 22,
        'e', 11,
        's', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(68);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '#') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(68);
      if (lookahead == '#') ADVANCE(66);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == 'c') ADVANCE(54);
      if (lookahead == 'e') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '#') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'v') ADVANCE(5);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == 'k') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'k') ADVANCE(45);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 36:
      if (lookahead == 'x') ADVANCE(30);
      END_STATE();
    case 37:
      if (lookahead == 'y') ADVANCE(48);
      END_STATE();
    case 38:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '@') ADVANCE(14);
      if (lookahead == '[') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_Subtask);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_ATextends);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_subtask);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_ATvalidator);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_copy);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_copy);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_echo);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_echo);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'c') ADVANCE(53);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'h') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'o') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'o') ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'p') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == 'y') ADVANCE(49);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"') ADVANCE(66);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(67);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\\') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_group_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(68);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 39},
  [3] = {.lex_state = 39},
  [4] = {.lex_state = 39},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 62},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 62},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_Subtask] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_ATextends] = ACTIONS(1),
    [anon_sym_subtask] = ACTIONS(1),
    [anon_sym_ATvalidator] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_copy] = ACTIONS(1),
    [anon_sym_echo] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym_subtask] = STATE(11),
    [sym_subtask_header] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_ATextends,
    ACTIONS(13), 1,
      anon_sym_ATvalidator,
    ACTIONS(15), 1,
      sym_group_name,
    STATE(3), 1,
      aux_sym_subtask_repeat1,
    STATE(20), 1,
      sym_item,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(35), 2,
      sym_extends,
      sym_validator,
    STATE(36), 2,
      sym_directive,
      sym_command,
  [31] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_ATextends,
    ACTIONS(13), 1,
      anon_sym_ATvalidator,
    ACTIONS(15), 1,
      sym_group_name,
    STATE(4), 1,
      aux_sym_subtask_repeat1,
    STATE(20), 1,
      sym_item,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(35), 2,
      sym_extends,
      sym_validator,
    STATE(36), 2,
      sym_directive,
      sym_command,
  [62] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_ATextends,
    ACTIONS(24), 1,
      anon_sym_ATvalidator,
    ACTIONS(27), 1,
      sym_group_name,
    STATE(4), 1,
      aux_sym_subtask_repeat1,
    STATE(20), 1,
      sym_item,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(35), 2,
      sym_extends,
      sym_validator,
    STATE(36), 2,
      sym_directive,
      sym_command,
  [93] = 8,
    ACTIONS(30), 1,
      anon_sym_copy,
    ACTIONS(32), 1,
      anon_sym_echo,
    ACTIONS(34), 1,
      sym_word,
    ACTIONS(36), 1,
      anon_sym_DQUOTE,
    ACTIONS(38), 1,
      sym_comment,
    STATE(8), 1,
      sym_arg,
    STATE(18), 1,
      sym_string_literal,
    STATE(32), 3,
      sym_copy,
      sym_echo,
      sym_script,
  [120] = 6,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym_word,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(46), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym_string_literal,
    STATE(6), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [140] = 6,
    ACTIONS(34), 1,
      sym_word,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym_string_literal,
    STATE(9), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [160] = 6,
    ACTIONS(34), 1,
      sym_word,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    ACTIONS(52), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym_string_literal,
    STATE(10), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [180] = 6,
    ACTIONS(34), 1,
      sym_word,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    ACTIONS(54), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym_string_literal,
    STATE(6), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [200] = 6,
    ACTIONS(34), 1,
      sym_word,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym_string_literal,
    STATE(6), 2,
      sym_arg,
      aux_sym_echo_repeat1,
  [220] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_subtask_header,
    STATE(12), 2,
      sym_subtask,
      aux_sym_source_file_repeat1,
  [237] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    STATE(2), 1,
      sym_subtask_header,
    STATE(12), 2,
      sym_subtask,
      aux_sym_source_file_repeat1,
  [254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_ATextends,
      anon_sym_ATvalidator,
      sym_group_name,
  [265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_ATextends,
      anon_sym_ATvalidator,
      sym_group_name,
  [276] = 5,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym_word,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_arg,
    STATE(29), 1,
      sym_string_literal,
  [292] = 5,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym_word,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_string_literal,
    STATE(33), 1,
      sym_arg,
  [308] = 3,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_LF,
    ACTIONS(71), 2,
      sym_word,
      anon_sym_DQUOTE,
  [319] = 3,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_LF,
    ACTIONS(75), 2,
      sym_word,
      anon_sym_DQUOTE,
  [330] = 3,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_LF,
    STATE(14), 1,
      sym__newline,
  [340] = 3,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_LF,
    STATE(13), 1,
      sym__newline,
  [350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
  [357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_subtask,
  [371] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(89), 1,
      aux_sym_string_literal_token1,
  [378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_number,
  [385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_Subtask,
  [392] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_LF,
  [399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_number,
  [406] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_LF,
  [413] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_LF,
  [420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_DQUOTE,
  [427] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LF,
  [434] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LF,
  [441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_SEMI,
  [448] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_LF,
  [455] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LF,
  [462] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_LF,
  [469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
  [476] = 2,
    ACTIONS(38), 1,
      sym_comment,
    ACTIONS(115), 1,
      aux_sym_string_literal_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 180,
  [SMALL_STATE(10)] = 200,
  [SMALL_STATE(11)] = 220,
  [SMALL_STATE(12)] = 237,
  [SMALL_STATE(13)] = 254,
  [SMALL_STATE(14)] = 265,
  [SMALL_STATE(15)] = 276,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 308,
  [SMALL_STATE(18)] = 319,
  [SMALL_STATE(19)] = 330,
  [SMALL_STATE(20)] = 340,
  [SMALL_STATE(21)] = 350,
  [SMALL_STATE(22)] = 357,
  [SMALL_STATE(23)] = 364,
  [SMALL_STATE(24)] = 371,
  [SMALL_STATE(25)] = 378,
  [SMALL_STATE(26)] = 385,
  [SMALL_STATE(27)] = 392,
  [SMALL_STATE(28)] = 399,
  [SMALL_STATE(29)] = 406,
  [SMALL_STATE(30)] = 413,
  [SMALL_STATE(31)] = 420,
  [SMALL_STATE(32)] = 427,
  [SMALL_STATE(33)] = 434,
  [SMALL_STATE(34)] = 441,
  [SMALL_STATE(35)] = 448,
  [SMALL_STATE(36)] = 455,
  [SMALL_STATE(37)] = 462,
  [SMALL_STATE(38)] = 469,
  [SMALL_STATE(39)] = 476,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask, 1, 0, 1),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask, 2, 0, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subtask_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_echo_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_echo_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_echo_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script, 1, 0, 2),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script, 2, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask_header, 5, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_validator, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copy, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_testplan(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "testplan",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
